### ISSUE TITLE
TypeError: spawn_async_1.default is not a function

### ISSUE THREAD

**Issue by ffflorian** [expo/spawn-async#18]
When I import `spawnAsync` in TypeScript like this:

```ts
import spawnAsync from '@expo/spawn-async';
// spawnAsync( ... )
```

And try running it, I get the error

```
TypeError: spawn_async_1.default is not a function
```

**Comment by ide** [comment]
Try setting `allowSyntheticDefaultImports` in your TypeScript configuration. This allows TS to import from CJS modules too.

**Comment by ide** [comment]
I added a test here to ensure that there isn't a regression: https://github.com/expo/spawn-async/commit/5cb842fc38a9ead6f049847596a48105893c9d53. If you would like to figure out a way to address your issue without `allowSyntheticDefaultImports`, please make sure the tests continue to pass (although I'm not sure it is possible).

**Comment by ffflorian** [comment]
> Try setting `allowSyntheticDefaultImports` in your TypeScript configuration. This allows TS to import from CJS modules too.

Alright, thanks!

**Comment by ffflorian** [comment]
In general I think it's easier to just export it as an object instead of using a default export and CJS hacks. But that's a different story :slightly_smiling_face:

**Comment by wjhurley** [comment]
I have `allowSyntheticDefaultImports` set in my `tsconfig.json` and I still get the same error.

**Comment by loganek** [comment]
Same here, could we re-open the issue?
