### ISSUE TITLE
Cannot use with ESM module

### ISSUE THREAD

**Issue by slhck** [expo/spawn-async#37]
I have a TypeScript project that I'm trying to convert to use ESM via the following options:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
   // ...
}
```

The code I used to have was like this:

```ts
import spawnAsync, { SpawnOptions, SpawnPromise, SpawnResult } from '@expo/spawn-async';

// ...

spawnAsync(…);
```

I am trying to run the project with `ts-node` (`ts-node --esm src/index.ts`), but now, I get this error on the call:

```
  Type 'typeof import("./node_modules/@expo/spawn-async/build/spawnAsync")' has no call signatures.

18   const proc = spawnAsync(cmd, args, opts);
                  ~~~~~~~~~~

    at createTSError (./node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (./node_modules/ts-node/src/index.ts:863:19)
    at getOutput (./node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (./node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (./node_modules/ts-node/src/esm.ts:400:37)
    at ./node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (./node_modules/ts-node/src/esm.ts:409:15)
    at async ESMLoader.load (node:internal/modules/esm/loader:303:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:47) {
  diagnosticCodes: [ 2349 ]
}
```

Notably, no other dependency I am using (out of 80-something) has this issue. I wonder if the exports of this project could be made in such a way that they work with both CommonJS and ESM?

**Comment by slhck** [comment]
I should add that once I change the call from `spawnAsync(…)` to `spawnAsync.default(…)` in my code, `ts-node` will run the code, but will barf when it actually calls the function, saying that `spawnAsync.default is not a function`.

**Comment by slhck** [comment]
I did a little bit of digging. Now, basically, the broken Node ecosystem is to blame for this being so complicated, but I suppose the way `yargs` is doing it could work.

They specify different entry points in their `package.json`: 

https://github.com/yargs/yargs/blob/f91d9b334ad9cfce79a89c08ff210c622b7c528f/package.json#L5-L32

There are two index files, one for [CommonJS](https://github.com/yargs/yargs/blob/main/index.cjs), and one as an [ES Module](https://github.com/yargs/yargs/blob/main/index.mjs). These apparently can live alongside each other — and depending on how the package is used, it'll pick the correct one.

**Comment by ide** [comment]
Writing a dual mode module with TypeScript brings a lot of baggage so I'd like to avoid that route if we can. CJS probably should work with export =. We don't have ESM projects that consume this package yet, it might be awhile before someone on our team need to look at this, in case you want to go ahead and figure things out.

**Comment by slhck** [comment]
Yeah, I realize it's probably not always worth the effort to go fully dual. I just wonder what makes it incompatible with my new module, since none of the other packages I am using has that issue.

I might try some workarounds but for now I think I'll manually vendor the dependency.
